version: '3.1'
services:
  nmrc-mysql:
    container_name: nmrc-mysql
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
      - mysql_data:/var/lib/mysql
      # - ./mysql/data:/var/lib/mysql
    working_dir: /usr/src/app
    ports:
      - 3307:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=nomurec
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=65yKFuZJ^cSF
    restart: 'no'
volumes:
  mysql_data: