version: "3.1"
services:
  nmrc-mysql:
    container_name: nmrc-mysql
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - ./mysql/docker.cnf:/etc/mysql/conf.d/docker.cnf
    working_dir: /usr/src/app
    ports:
      - 13306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_DATABASE=nomurec
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=appuser
    restart: "no"
