name: Upload artifacts to AWS S3

on:
  push:
    # Trigger if there are changes in dev, stg, and prd branches
    # Remove main
    branches: [dev, stg, prd, main]
permissions:    # This is required for actions/checkout
  id-token: write
  contents: read

jobs:
  deploy:
    name: Upload to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        
      - name: Set environment profile
        run: |
          branch="$(echo $GITHUB_REF | cut -d'/' -f 3)"
          echo $branch
          if [ $branch = 'dev']; then
              echo "It is dev environment"
              echo "PROFILE=dev" >> "$GITHUB_ENV"
              echo "IAM_ROLE_ARN=arn:aws:iam::441196140625:role/ced-rnd-s3-role" >> "$GITHUB_ENV"
          else
              echo "Invalid environment."
              echo "PROFILE=null" >> "$GITHUB_ENV"
              echo "IAM_ROLE_ARN=null" >> "$GITHUB_ENV"
          fi
        
      - name: Test
        run: |
          echo $PROFILE
          echo $IAM_ROLE_ARN
          
