name: Upload artifacts to AWS S3

on:
  push:
    # Trigger if there are changes in dev, stg, and prd branches
    # Remove main
    branches: [dev, stg, prd, main]

jobs:
  deploy:
    name: Upload to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::441196140625:role/ced-rnd-s3-role
          role-duration-seconds: 1200
          role-session-name: nmrc-dev

      - name: Zip artifacts
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: 'src.zip'
          exclusions: '*.git* /*target/*'

      - name: Upload to AWS S3 (develop)
        if: github.ref == 'refs/heads/dev'
        run: |
          echo Uploading artifacts to DEV environment.
          aws s3 cp src.zip s3://nmrc-dev-cicd-bucket/${{ secrets.CI_PROJECT_NAME }}/
      - name: Upload to AWS S3 (staging)
        if: github.ref == 'refs/heads/stg'
        run: |
          echo Uploading artifacts to STG environment.
          aws s3 cp src.zip s3://nmrc-stg-cicd-bucket/${{ secrets.CI_PROJECT_NAME }}/
      - name: Upload to AWS S3 (production)
        if: github.ref == 'refs/heads/prd'
        run: |
          echo Uploading artifacts to PRD environment.
          aws s3 cp src.zip s3://nmrc-prd-cicd-bucket/${{ secrets.CI_PROJECT_NAME }}/
